kind: pipeline 
name: default 
type: kubernetes
steps:
- name: publish  
  image: plugins/ecr
  settings:
    access_key:
      from_secret: aws_access_key
    secret_key:
      from_secret: aws_secret_access_key
    repo: 659994610574.dkr.ecr.us-east-1.amazonaws.com/drone-ecr-repo
    registry: 659994610574.dkr.ecr.us-east-1.amazonaws.com
- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 18.232.133.66
    username: ubuntu
    port: 22
    key:
      from_secret: ssh_key
      script:
        - sudo chown ubuntu:ubuntu /var/run/docker.sock
        - sudo aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 659994610574.dkr.ecr.us-east-1.amazonaws.com
        - sudo docker pull 659994610574.dkr.ecr.us-east-1.amazonaws.com/apacheimage:latest
        - sudo docker run -idt -p 8080:80 --name apache 659994610574.dkr.ecr.us-east-1.amazonaws.com/apacheimage:latest    
 
